# 7장 오류 처리

## 구성
1. [오류 코드보다 예외를 사용하라](#오류-코드보다-예외를-사용하라)
2. [Try-Catch-Finally 문부터 작성하라](#try-catch-finally-문부터-작성하라)
3. [미확인 예외를 사용하라](#미확인-예외를-사용하라)
4. [예외에 의미를 제공하라](#예외에-의미를-제공하라)
5. [호출자를 고려해 예외 클래스를 정의하라](#호출자를-고려해-예외-클래스를-정의하라)
6. [정상 흐름을 정의하라](#정상-흐름을-정의하라)
7. [null을 반환하지 마라](#null을-반환하지-마라)
8. [null을 전달하지 마라](#null을-전달하지-마라)

## 오류 코드보다 예외를 사용하라
- 예전엔 예외를 지원하지 않는 프로그래밍 언어가 많았다. 따라서 에러 flag 혹은 에러 코드를 반환하는 방법으로 처리했다.
- 에러 코드를 이용하는 방법은 오류가 날 때 바로 오류를 처리해야하므로 예외 처리와 비즈니스 로직을 분리하기 어렵고 결과적으로 실수를 하게 만든다.

```java
// Bad
public class DeviceController {
  ...
  public void sendShutDown() {
    DeviceHandle handle = getHandle(DEV1);
    // Check the state of the device
    if (handle != DeviceHandle.INVALID) {
      // Save the device status to the record field
      retrieveDeviceRecord(handle);
      // If not suspended, shut down
      if (record.getStatus() != DEVICE_SUSPENDED) {
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
      } else {
        logger.log("Device suspended. Unable to shut down");
      }
    } else {
      logger.log("Invalid handle for: " + DEV1.toString());
    }
  }
  ...
}
```

```java
// Good
public class DeviceController {
  ...
  public void sendShutDown() {
    try {
      tryToShutDown();
    } catch (DeviceShutDownError e) {
      logger.log(e);
    }
  }
    
  private void tryToShutDown() throws DeviceShutDownError {
    DeviceHandle handle = getHandle(DEV1);
    DeviceRecord record = retrieveDeviceRecord(handle);
    pauseDevice(handle); 
    clearDeviceWorkQueue(handle); 
    closeDevice(handle);
  }
  
  private DeviceHandle getHandle(DeviceID id) {
    ...
    throw new DeviceShutDownError("Invalid handle for: " + id.toString());
    ...
  }
  ...
}
```

각 개념을 독립적으로 살펴보고 이해할 수 있다.

## Try-Catch-Finally 문부터 작성하라
- `try` 블록에서 어떠한 일이 생기든지 `catch` 블록은 프로그램 상태를 일관성 있게 유지할 수 있다.
- 따라서 예외가 발생할 코드를 짤 때는 `try-catch-finally` 문으로 시작하는 편이 낫다.
- `try` 문이 하나의 `scope` 가 된다.

```java
  // Step 1: StorageException을 던지지 않으므로 이 테스트는 실패한다.
  @Test(expected = StorageException.class)
  public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
  }
  
  public List<RecordedGrip> retrieveSection(String sectionName) {
    // dummy return until we have a real implementation
    return new ArrayList<RecordedGrip>();
  }
```

```java
  // Step 2: StorageException을 던졌으므로 이제 테스트는 통과한다.
  @Test(expected = StorageException.class)
  public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
  }

  public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName)
    } catch (Exception e) {
      throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
  }
```

```java
  // Step 3: Exception의 범위를 FileNotFoundException으로 줄여 정확히 어떤 Exception이 발생한지 체크하자.
    @Test(expected = StorageException.class)
  public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
  }
  
  public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName);
      stream.close();
    } catch (FileNotFoundException e) {
      throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
  }
```

강제로 예외를 일으키는 테스트 케이스를 작성한 후 테스트를 통과하게 코드를 작성하는 방법을 권장한다. 자연스럽게 `try` 블록의 트랜잭션 범위부터 구현하게 되므로 범위 내에서 트랜잭션 본질을 유지하기 쉬워진다.

## 미확인 예외를 사용하라
- 과거에는 메서드를 선언할 때는 메서드가 반환할 예외를 모두 열거했다. 하지만 요즘은 사용하지 않는다. 확인된 오류가 치르는 **비용**이 상당히 크다.
- 확인된 예외는 OCP 를 위반한다. 
  - 메서드에서 확인된 예외를 던졌는데 `catch` 블록이 세 단계 위에 있다면 그 사이 메서드 모두가 선언부에 해당 예외를 정의해야 한다.
  - 하위 단계에서 코드를 변경하면 상위 단계 메서드 선언부를 전부 고쳐야 한다.(메소드 선언에 throws 구문을 붙이는 등의 작업)
  - throws 경로에 위치하는 모든 함수가 최하위 함수에서 던지는 예외를 알아야 하므로 `캡슐화`가 깨진다.
- 아주 중요한 라이브러리를 작성한다면 모든 예외를 잡아야 한다. 하지만 일반적인 앱에서 `의존성`이라는 비용이 더 든다.

## 예외에 의미를 제공하라
- 예외를 던질 때는 전후 상황을 충분히 덧붙인다.
- 오류 메시지에 정보를 담아 예외와 함께 던진다. (실패한 연산 이름과 실패 유형도 언급)
- 로깅 기능을 사용한다면 catch 블록에서 오류를 기록하도록 충분한 정보를 넘겨준다.

## 호출자를 고려해 예외 클래스를 정의하라
오류를 분류하는 방식은 수 없이 많다.

1. 오류가 발생한 위치
   1. 컴포넌트로 분류
2. 오류의 유형
   1. 디바이스 실패
   2. 네트워크 실패
   3. 프로그래밍 오류

하지만 앱에서 오류를 정의할 때 프로그래머에게 가장 중요한 관심사는 **오류를 잡아내는 방법**이 되어야 한다.

```java
  // Bad
  ACMEPort port = new ACMEPort(12);
  try {
    port.open();
  } catch (DeviceResponseException e) {
    reportPortError(e);
    logger.log("Device response exception", e);
  } catch (ATM1212UnlockedException e) {
    reportPortError(e);
    logger.log("Unlock exception", e);
  } catch (GMXError e) {
    reportPortError(e);
    logger.log("Device response exception");
  } finally {
    ...
  }
```
외부 라이브러리를 호출하는 코드에서 catch 문의 내용이 거의 같다. 또한, 외부 라이브러리가 던질 예외를 모두 잡는다.

```java
  // Good
  LocalPort port = new LocalPort(12);
  try {
    port.open();
  } catch (PortDeviceFailure e) {
    reportError(e);
    logger.log(e.getMessage(), e);
  } finally {
    ...
  }
  
  public class LocalPort {
    private ACMEPort innerPort;
    public LocalPort(int portNumber) {
      innerPort = new ACMEPort(portNumber);
    }
    
    public void open() {
      try {
        innerPort.open();
      } catch (DeviceResponseException e) {
        throw new PortDeviceFailure(e);
      } catch (ATM1212UnlockedException e) {
        throw new PortDeviceFailure(e);
      } catch (GMXError e) {
        throw new PortDeviceFailure(e);
      }
    }
    ...
  }
```
ACME 클래스를 LocalPort 클래스로 래핑해 new ACMEPort().open() 메소드에서 던질 수 있는 exception들을 간략화했다. 외부 API 를 감싸면 외부 라이브러리와 프로그램 사이의 의존성이 크게 줄어든다. 다른 API 로 갈아탈때도 부담이 훨씬 줄어들게 된다.

## 정상 흐름을 정의하라
- 외부 API를 감싸 독자적인 예외를 던지고 코드 위에 처리기를 정의해 중단된 계산을 처리한다. 대게는 괜찮지만, 때로는 중단이 적합하지 않는 때도 있다.
- 특히, 코드를 부르는 입장에서 `예외적인 상황`을 항상 고려해야 한다면 부담이 된다. 이런 경우 특수 사례 패턴(SPECIAL CASE PATTERN)을 사용해 클라이언트 코드가 예외적인 상황을 처리할 필요가 없도록 만든다.

```java
  // Bad
  try {
    MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
    m_total += expenses.getTotal();
  } catch(MealExpensesNotFound e) {
    m_total += getMealPerDiem();
  }
```
함수를 호출하는 시점에서 예외 상황의 예상되어 예외처리가 들어갔다. 예외가 논리를 따라가기 어렵게 만든다.

```java
  // Good
  MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
  m_total += expenses.getTotal();
  ////////////////////////
  public class PerDiemMealExpenses implements MealExpenses {
    public int getTotal() {
      // 기본값으로 일일 기본 식비를 반환한다.
    }
  }
  // Detail
  public class ExpenseReportDAO {
    public MealExpenses getMeals(int employeeId) {
      MealExpenses expenses;
      try {
        expenses = expenseReportDAO.getMeals(employee.getID());
      } catch(MealExpensesNotFound e) {
        expenses = new PerDiemMealExpenses();
      } 
      return expenses;
    }
  }
```
특수 사례 패턴을 통해서 해결한다. 클래스를 만들거나 객체를 조작해 특수 사례를 처리하는 방식이다. 클라이언트 코드에서 예외적인 상황을 처리할 필요가 없어진다.

## null을 반환하지 마라
오류를 유발하는 행위 중 첫번째는 `null`을 반환하는 코드이다. `null`을 반환하는 코드는 일거리를 늘릴 뿐만 아니라 호출자에게 문제를 떠넘긴다.

```java
  // BAD
  public void registerItem(Item item) {
    if (item != null) {
      ItemRegistry registry = peristentStore.getItemRegistry();
      if (registry != null) {
        Item existing = registry.getItem(item.getID());
        if (existing.getBillingPeriod().hasRetailOwner()) {
          existing.register(item);
        }
      }
    }
  }
  // Bad
  List<Employee> employees = getEmployees();
  if (employees != null) {
    for(Employee e : employees) {
      totalPay += e.getPay();
    }
  }
```

누구 하나라도 `null`을 체크하는 로직을 빼먹는다면 앱이 통제 불능에 빠질지도 모른다.

```java
  // Good
  List<Employee> employees = getEmployees();
  for(Employee e : employees) {
    totalPay += e.getPay();
  }
  
  public List<Employee> getEmployees() {
    if( .. there are no employees .. )
      return Collections.emptyList();
    }
  }
```

메서드에서 null을 반환하고 싶은 유혹이 든다면 예외를 던지거나 특수 사례 객체를 반환한다. 사용하려는 외부 API가 `null`을 반환한다면 감싸기 메서드를 구현해 예외를 던지거나 `특수 사례 객체`를 반환하는 방식을 고려한다.

## null을 전달하지 마라
오류를 유발하는 행위 중 두번째는 메서드에 `null`을 전달하는 코드이다. `null`을 반환하는 코드보다 더 나쁘다.

```java
// Bad
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    return (p2.x – p1.x) * 1.5;
  }
  ...
}
```
calculator.xProjection(null, new Point(12, 13)); 위와 같이 부를 경우 NullPointerException 발생한다.
```java
// Bad
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    if(p1 == null || p2 == null){
      throw InvalidArgumentException("Invalid argument for MetricsCalculator.xProjection");
    }
    return (p2.x – p1.x) * 1.5;
  }
}
```
NullPointerException은 안나지만 윗단계에서 InvalidArgumentException이 발생할 경우 처리해줘야한다.
```java
// Bad
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    assert p1 != null : "p1 should not be null";
    assert p2 != null : "p2 should not be null";
    
    return (p2.x – p1.x) * 1.5;
  }
}
```
좋은 명세이지만 첫번째 예시와 같이 NullPointerException 문제를 해결하지 못한다.